package org.gvt.util;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * A merge of Cosmic Cancer Census and OncoKB.
 *
 */
public class CancerGenes
{
	public static boolean isCancerGene(String gene)
	{
		return genes.contains(gene);
	}

	private static final Set<String> genes = new HashSet<String>(Arrays.asList(
		("RB1\n" +
		"ATF1\n" +
		"MDC1\n" +
		"RPL5\n" +
		"PRSS1\n" +
		"CHIC2\n" +
		"MAML2\n" +
		"TFRC\n" +
		"TRRAP\n" +
		"ARAF\n" +
		"ELK4\n" +
		"PREX2\n" +
		"HOXA9\n" +
		"SOX17\n" +
		"TFG\n" +
		"CLP1\n" +
		"AKT2\n" +
		"MYC\n" +
		"CREB3L1\n" +
		"AKT3\n" +
		"CREB3L2\n" +
		"MYB\n" +
		"AKT1\n" +
		"PWWP2A\n" +
		"PRKACA\n" +
		"MNX1\n" +
		"NUP214\n" +
		"DAXX\n" +
		"MEF2B\n" +
		"FNBP1\n" +
		"RPL22\n" +
		"DDX10\n" +
		"DICER1\n" +
		"SND1\n" +
		"NUP93\n" +
		"BCR\n" +
		"EML4\n" +
		"AR\n" +
		"PRKAR1A\n" +
		"EWSR1\n" +
		"DDIT3\n" +
		"NUP98\n" +
		"TCL6\n" +
		"ZNF278\n" +
		"SET\n" +
		"RPN1\n" +
		"PDGFB\n" +
		"XPA\n" +
		"XPC\n" +
		"BCL10\n" +
		"GATA3\n" +
		"GATA2\n" +
		"GATA1\n" +
		"MEF2BNB-MEF2B\n" +
		"HIF1A\n" +
		"GRIN2A\n" +
		"RNF213\n" +
		"TERT\n" +
		"RAD21\n" +
		"PRDM16\n" +
		"PLCG2\n" +
		"NKX2-1\n" +
		"VTI1A\n" +
		"PLCG1\n" +
		"BARD1\n" +
		"CREBBP\n" +
		"JUN\n" +
		"ZNF384\n" +
		"H3F3B\n" +
		"H3F3C\n" +
		"PLK2\n" +
		"H3F3A\n" +
		"NFATC2\n" +
		"BRAF\n" +
		"FLI1\n" +
		"PBX1\n" +
		"COL1A1\n" +
		"MLLT11\n" +
		"CYLD\n" +
		"MLLT10\n" +
		"PPFIBP1\n" +
		"KIAA1598\n" +
		"FAT1\n" +
		"REL\n" +
		"STRN\n" +
		"CDK12\n" +
		"FAT4\n" +
		"EZH2\n" +
		"CEP89\n" +
		"RET\n" +
		"ITK\n" +
		"SETD2\n" +
		"CDKN1A\n" +
		"CDKN1B\n" +
		"BTG1\n" +
		"ELL\n" +
		"ELN\n" +
		"CLTC\n" +
		"CTCF\n" +
		"HOXC13\n" +
		"GLI1\n" +
		"HOXC11\n" +
		"PHF6\n" +
		"BBC3\n" +
		"MED12\n" +
		"IKBKB\n" +
		"ATIC\n" +
		"HEY1\n" +
		"MECOM\n" +
		"RSPO2\n" +
		"CTLA4\n" +
		"RSPO3\n" +
		"JAK2\n" +
		"CIC\n" +
		"IKBKE\n" +
		"JAK3\n" +
		"JAK1\n" +
		"BRD3\n" +
		"SS18\n" +
		"RMI2\n" +
		"IFNGR1\n" +
		"FCRL4\n" +
		"TCF12\n" +
		"TET2\n" +
		"TET1\n" +
		"PAX3\n" +
		"PAX5\n" +
		"POU5F1\n" +
		"DDB2\n" +
		"NCOR2\n" +
		"NCOR1\n" +
		"COL2A1\n" +
		"SDHAF2\n" +
		"PAX8\n" +
		"TAL2\n" +
		"PAX7\n" +
		"TAL1\n" +
		"RARA\n" +
		"POT1\n" +
		"PPARG\n" +
		"PAFAH1B2\n" +
		"GAS7\n" +
		"FH\n" +
		"RPL10\n" +
		"GPS2\n" +
		"HOXD13\n" +
		"HOXD11\n" +
		"RUNDC2A\n" +
		"CENPA\n" +
		"EGFR\n" +
		"FSTL3\n" +
		"RECQL4\n" +
		"NRAS\n" +
		"WRN\n" +
		"EPCAM\n" +
		"NSD1\n" +
		"SPOP\n" +
		"PMS2\n" +
		"RICTOR\n" +
		"STAT6\n" +
		"SF3B1\n" +
		"PMS1\n" +
		"BRD4\n" +
		"RUNX1T1\n" +
		"CDKN2B\n" +
		"CDKN2C\n" +
		"CDKN2A\n" +
		"STAT3\n" +
		"KTN1\n" +
		"RYBP\n" +
		"WT1\n" +
		"RFWD2\n" +
		"NFIB\n" +
		"ETNK1\n" +
		"ABI1\n" +
		"CCDC6\n" +
		"GOPC\n" +
		"INHA\n" +
		"CRLF2\n" +
		"ZNF331\n" +
		"CSF3R\n" +
		"IRS1\n" +
		"NAB2\n" +
		"CASC5\n" +
		"IRS2\n" +
		"MSI2\n" +
		"PARK2\n" +
		"FGF3\n" +
		"FGF4\n" +
		"STK11\n" +
		"CDH1\n" +
		"PIM1\n" +
		"SSX4\n" +
		"NBN\n" +
		"SSX2\n" +
		"ROS1\n" +
		"WHSC1L1\n" +
		"MEN1\n" +
		"SSX1\n" +
		"NUTM2A\n" +
		"RNF43\n" +
		"MAP2K4\n" +
		"USP8\n" +
		"MAP2K1\n" +
		"MAP2K2\n" +
		"USP6\n" +
		"TPM4\n" +
		"EIF1AX\n" +
		"FBXW7\n" +
		"TPM3\n" +
		"MITF\n" +
		"FBXO11\n" +
		"FOXP1\n" +
		"MSH6\n" +
		"CLIP1\n" +
		"MAF\n" +
		"SMO\n" +
		"MSH2\n" +
		"KAT6B\n" +
		"KAT6A\n" +
		"RAB35\n" +
		"SRSF2\n" +
		"SRSF3\n" +
		"PGR\n" +
		"MALAT1\n" +
		"ERG\n" +
		"IL6ST\n" +
		"NUTM2B\n" +
		"NOTCH2\n" +
		"NOTCH3\n" +
		"KMT2D\n" +
		"CSF1R\n" +
		"CD274\n" +
		"BLM\n" +
		"DNMT1\n" +
		"NOTCH1\n" +
		"KMT2A\n" +
		"CBFB\n" +
		"MAX\n" +
		"KMT2C\n" +
		"NOTCH4\n" +
		"ANKRD11\n" +
		"CUL3\n" +
		"GMPS\n" +
		"VTCN1\n" +
		"FOXO4\n" +
		"FOXO3\n" +
		"FHIT\n" +
		"FOXO1\n" +
		"SOCS1\n" +
		"BCL2L11\n" +
		"CLTCL1\n" +
		"TPR\n" +
		"UBR5\n" +
		"ABL1\n" +
		"ABL2\n" +
		"TNFRSF17\n" +
		"TNFRSF14\n" +
		"KDSR\n" +
		"SRGAP3\n" +
		"CD276\n" +
		"MCL1\n" +
		"CDKN2A(p14)\n" +
		"FUS\n" +
		"ZBTB16\n" +
		"FANCA\n" +
		"FANCC\n" +
		"FANCE\n" +
		"PALB2\n" +
		"FANCG\n" +
		"QKI\n" +
		"FANCF\n" +
		"NFKB2\n" +
		"PTPRD\n" +
		"CDK8\n" +
		"BCL9\n" +
		"PTPRB\n" +
		"CDK6\n" +
		"MAFB\n" +
		"PTPRC\n" +
		"BCL6\n" +
		"CDK4\n" +
		"RHEB\n" +
		"BCL5\n" +
		"NACA\n" +
		"BCL3\n" +
		"CNOT3\n" +
		"NF1\n" +
		"BCL2\n" +
		"MDM2\n" +
		"FGFR1OP\n" +
		"MDM4\n" +
		"NF2\n" +
		"MAP3K13\n" +
		"LZTR1\n" +
		"MAP3K14\n" +
		"MYD88\n" +
		"BCL2L1\n" +
		"NFE2L2\n" +
		"ALK\n" +
		"CIITA\n" +
		"TRA\n" +
		"FLT1\n" +
		"HSP90AB1\n" +
		"NUMA1\n" +
		"FLT3\n" +
		"TRB\n" +
		"FLT4\n" +
		"TRD\n" +
		"PTEN\n" +
		"PIK3CD\n" +
		"PIK3C2G\n" +
		"PIK3CB\n" +
		"PIK3CG\n" +
		"CDC73\n" +
		"PPP6C\n" +
		"KIAA1549\n" +
		"DNMT3B\n" +
		"ERC1\n" +
		"ZNF521\n" +
		"NKX3-1\n" +
		"HSP90AA1\n" +
		"DIS3\n" +
		"ATRX\n" +
		"DNMT3A\n" +
		"ARNT\n" +
		"FOXL2\n" +
		"TRAF2\n" +
		"NRG1\n" +
		"TRAF7\n" +
		"DUX4L1\n" +
		"PIK3CA\n" +
		"LCK\n" +
		"PIK3C3\n" +
		"TOP1\n" +
		"LCP1\n" +
		"MET\n" +
		"BIRC3\n" +
		"SMARCD1\n" +
		"CEBPA\n" +
		"NUTM1\n" +
		"CANT1\n" +
		"SRC\n" +
		"PLAG1\n" +
		"PRCC\n" +
		"U2AF1\n" +
		"MLLT1\n" +
		"PPM1D\n" +
		"MLLT3\n" +
		"MLLT4\n" +
		"TTL\n" +
		"MALT1\n" +
		"MLLT6\n" +
		"P2RY8\n" +
		"DNAJB1\n" +
		"FIP1L1\n" +
		"IL21R\n" +
		"FYN\n" +
		"E2F3\n" +
		"SH2B3\n" +
		"EIF4E\n" +
		"JAZF1\n" +
		"NTRK1\n" +
		"SMARCE1\n" +
		"NTRK2\n" +
		"KCNJ5\n" +
		"PRRX1\n" +
		"NTRK3\n" +
		"MGA\n" +
		"CNBP\n" +
		"PTPN11\n" +
		"KLF4\n" +
		"PTPN13\n" +
		"MTOR\n" +
		"TBX3\n" +
		"PNRC1\n" +
		"PML\n" +
		"RAD52\n" +
		"ASXL1\n" +
		"RAD50\n" +
		"KLF6\n" +
		"NIN\n" +
		"RAD51\n" +
		"APC\n" +
		"POU2AF1\n" +
		"ASXL2\n" +
		"EIF3E\n" +
		"BCOR\n" +
		"PDCD1\n" +
		"FCGR2B\n" +
		"TRIM33\n" +
		"EIF4A2\n" +
		"ERRFI1\n" +
		"SMARCB1\n" +
		"PRF1\n" +
		"KEAP1\n" +
		"CBLC\n" +
		"CBLB\n" +
		"IKZF1\n" +
		"CRKL\n" +
		"RPS6KA4\n" +
		"SOX2\n" +
		"TCL1A\n" +
		"GOLGA5\n" +
		"HMGN2P46\n" +
		"PPP2R1A\n" +
		"CHEK2\n" +
		"CHEK1\n" +
		"KDR\n" +
		"TRIM24\n" +
		"SOX9\n" +
		"TRIM27\n" +
		"EPHB1\n" +
		"B2M\n" +
		"TP63\n" +
		"ICOSLG\n" +
		"EPHA5\n" +
		"ACVR1\n" +
		"SLC34A2\n" +
		"EPHA7\n" +
		"OMD\n" +
		"ACSL6\n" +
		"EBF1\n" +
		"HNF1A\n" +
		"HLA-A\n" +
		"ACSL3\n" +
		"RUNX1\n" +
		"INPP4A\n" +
		"INPP4B\n" +
		"MDS2\n" +
		"HIST2H3A\n" +
		"AKAP9\n" +
		"BTK\n" +
		"MTCP1\n" +
		"HIST2H3D\n" +
		"BCORL1\n" +
		"EZR\n" +
		"HIST2H3C\n" +
		"TP53\n" +
		"EPHA3\n" +
		"SLC45A3\n" +
		"HIST1H3J\n" +
		"SDC4\n" +
		"EPAS1\n" +
		"DCUN1D1\n" +
		"PIK3R3\n" +
		"PIK3R2\n" +
		"MST1R\n" +
		"PIK3R1\n" +
		"KLK2\n" +
		"CD79B\n" +
		"CD79A\n" +
		"C2orf44\n" +
		"BRIP1\n" +
		"HIST1H3A\n" +
		"HIST1H3F\n" +
		"HIST1H3G\n" +
		"HIST1H3H\n" +
		"HIST1H3I\n" +
		"HIST1H3B\n" +
		"HIST1H3C\n" +
		"RALGDS\n" +
		"RBM10\n" +
		"HIST1H3D\n" +
		"HIST1H3E\n" +
		"STAT5A\n" +
		"ZRSR2\n" +
		"STAT5B\n" +
		"WWTR1\n" +
		"YES1\n" +
		"BCL11B\n" +
		"BCL11A\n" +
		"INSR\n" +
		"XRCC2\n" +
		"SS18L1\n" +
		"SH2D1A\n" +
		"RANBP17\n" +
		"IGF2\n" +
		"MYO5A\n" +
		"PTK6\n" +
		"IGF1\n" +
		"SMARCA4\n" +
		"EXT1\n" +
		"EXT2\n" +
		"STAG2\n" +
		"FUBP1\n" +
		"ID3\n" +
		"ATM\n" +
		"HIST1H4I\n" +
		"CALR\n" +
		"BAP1\n" +
		"ATR\n" +
		"APOBEC3B\n" +
		"PTPRT\n" +
		"PTPRS\n" +
		"HIP1\n" +
		"BRCA1\n" +
		"PCSK7\n" +
		"PTPRK\n" +
		"BRCA2\n" +
		"HERPUD1\n" +
		"RPTOR\n" +
		"PCM1\n" +
		"XPO1\n" +
		"SUFU\n" +
		"CNTRL\n" +
		"RAC1\n" +
		"HRAS\n" +
		"IL10\n" +
		"NCOA1\n" +
		"NCOA2\n" +
		"PBRM1\n" +
		"SYK\n" +
		"PARP1\n" +
		"NCOA3\n" +
		"MST1\n" +
		"NCOA4\n" +
		"TFE3\n" +
		"TFEB\n" +
		"RHOH\n" +
		"PDCD1LG2\n" +
		"CBFA2T3\n" +
		"RHOA\n" +
		"MLF1\n" +
		"RAD51B\n" +
		"MN1\n" +
		"RAD51D\n" +
		"RAD51C\n" +
		"KIT\n" +
		"STK40\n" +
		"DDR2\n" +
		"YAP1\n" +
		"AMER1\n" +
		"DOT1L\n" +
		"WAS\n" +
		"TMPRSS2\n" +
		"XIAP\n" +
		"CXCR4\n" +
		"ALOX12B\n" +
		"PAK1\n" +
		"CUX1\n" +
		"WIF1\n" +
		"LMNA\n" +
		"PAK7\n" +
		"GPC3\n" +
		"RAD54L\n" +
		"TCEB1\n" +
		"EPS15\n" +
		"SUZ12\n" +
		"RANBP2\n" +
		"CD74\n" +
		"NPM1\n" +
		"MAP3K1\n" +
		"CDX2\n" +
		"FAM46C\n" +
		"MRE11A\n" +
		"IGH\n" +
		"MLH1\n" +
		"COX6C\n" +
		"IGK\n" +
		"VEGFA\n" +
		"IGL\n" +
		"PER1\n" +
		"RIT1\n" +
		"AXL\n" +
		"HNRNPA2B1\n" +
		"CTNNB1\n" +
		"FAS\n" +
		"TCEA1\n" +
		"TRIP11\n" +
		"FOXA1\n" +
		"CARS\n" +
		"CRTC3\n" +
		"CRTC1\n" +
		"MPL\n" +
		"BUB1B\n" +
		"PRDM1\n" +
		"HOXA13\n" +
		"IGF1R\n" +
		"HOXA11\n" +
		"CCND3\n" +
		"CCND2\n" +
		"CCND1\n" +
		"KIF5B\n" +
		"CHCHD7\n" +
		"EP300\n" +
		"ARID2\n" +
		"SH3GL1\n" +
		"PDGFRB\n" +
		"LMO1\n" +
		"PDGFRA\n" +
		"HGF\n" +
		"LMO2\n" +
		"TSC2\n" +
		"ARID5B\n" +
		"TSC1\n" +
		"SDHC\n" +
		"LIFR\n" +
		"SDHD\n" +
		"SDHA\n" +
		"SDHB\n" +
		"CCNB1IP1\n" +
		"MYCL\n" +
		"MYCN\n" +
		"SHQ1\n" +
		"CCNE1\n" +
		"FANCD2\n" +
		"TBL1XR1\n" +
		"SBDS\n" +
		"RAF1\n" +
		"CARD11\n" +
		"HIST1H2BD\n" +
		"ZCCHC8\n" +
		"DDX6\n" +
		"DDX5\n" +
		"CACNA1D\n" +
		"HOXB13\n" +
		"LPP\n" +
		"NDRG1\n" +
		"NCKIPSD\n" +
		"TMEM127\n" +
		"PMAIP1\n" +
		"C15orf65\n" +
		"CAMTA1\n" +
		"MYH11\n" +
		"SMAD2\n" +
		"SPECC1\n" +
		"SMAD4\n" +
		"ZFHX3\n" +
		"STIL\n" +
		"SMAD3\n" +
		"LHFP\n" +
		"IDH1\n" +
		"PTCH1\n" +
		"NONO\n" +
		"IDH2\n" +
		"ASPSCR1\n" +
		"HMGA1\n" +
		"HMGA2\n" +
		"MSN\n" +
		"INHBA\n" +
		"HOOK3\n" +
		"ARHGAP26\n" +
		"ESR1\n" +
		"PHOX2B\n" +
		"IL2\n" +
		"LRP1B\n" +
		"NFKBIA\n" +
		"NR4A3\n" +
		"TLX3\n" +
		"FGF19\n" +
		"GNAQ\n" +
		"FEV\n" +
		"TLX1\n" +
		"FAM175A\n" +
		"GNAS\n" +
		"TCF3\n" +
		"FGFR4\n" +
		"IL7R\n" +
		"NFKBIE\n" +
		"FGFR3\n" +
		"LSM14A\n" +
		"FGFR2\n" +
		"FGFR1\n" +
		"BMPR1A\n" +
		"PICALM\n" +
		"KDM5A\n" +
		"YWHAE\n" +
		"GSK3B\n" +
		"KDM5C\n" +
		"DDX3X\n" +
		"TNFAIP3\n" +
		"C12orf9\n" +
		"PSIP1\n" +
		"CHD4\n" +
		"AFF3\n" +
		"AFF4\n" +
		"AFF1\n" +
		"GPHN\n" +
		"FLCN\n" +
		"LYL1\n" +
		"SEPT9\n" +
		"LASP1\n" +
		"SEPT6\n" +
		"CASP8\n" +
		"ALDH2\n" +
		"BCL7A\n" +
		"WHSC1\n" +
		"POLE\n" +
		"HIST1H1C\n" +
		"KDM6A\n" +
		"EGFL7\n" +
		"ARHGEF12\n" +
		"RBM15\n" +
		"RNF217-AS1\n" +
		"PDPK1\n" +
		"EED\n" +
		"MKL1\n" +
		"AXIN1\n" +
		"ETV1\n" +
		"AXIN2\n" +
		"OLIG2\n" +
		"ARID1A\n" +
		"ARID1B\n" +
		"ETV4\n" +
		"SEPT5\n" +
		"TGFBR1\n" +
		"ETV5\n" +
		"TGFBR2\n" +
		"ETV6\n" +
		"DNM2\n" +
		"GREM1\n" +
		"LATS1\n" +
		"SFPQ\n" +
		"LATS2\n" +
		"CREB1\n" +
		"RABEP1\n" +
		"SETBP1\n" +
		"IRF4\n" +
		"ELF4\n" +
		"THRAP3\n" +
		"RASA1\n" +
		"MYOD1\n" +
		"H3F3AP4\n" +
		"CDH11\n" +
		"MYH9\n" +
		"ECT2L\n" +
		"ZNF198\n" +
		"HLF\n" +
		"DCTN1\n" +
		"LEF1\n" +
		"RAP1GDS1\n" +
		"ATP1A1\n" +
		"CBL\n" +
		"NT5C2\n" +
		"AURKB\n" +
		"AURKA\n" +
		"TFPT\n" +
		"MUC1\n" +
		"ERBB3\n" +
		"ERBB4\n" +
		"POLD1\n" +
		"GNA11\n" +
		"ERBB2\n" +
		"MAPK1\n" +
		"DROSHA\n" +
		"LRIG3\n" +
		"VHL\n" +
		"MUTYH\n" +
		"MAPK3\n" +
		"SPEN\n" +
		"TCF7L2\n" +
		"TAF15\n" +
		"NEGR1\n" +
		"ATP2B3\n" +
		"PDE4DIP\n" +
		"DEK\n" +
		"TSHR\n" +
		"ERCC3\n" +
		"ERCC4\n" +
		"FAM131B\n" +
		"ERCC2\n" +
		"HIST3H3\n" +
		"RPS6KB2\n" +
		"ACKR3\n" +
		"KRAS\n" +
		"ERCC5").split("\n")));

	public static void main(String[] args)
	{
		System.out.println("genes = " + genes.size());
	}
}
